server:
  port: 8081

spring:
  application:
    name: product-service

  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        scheme: http
        deregister: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
      minimum-idle: 5

  jackson:
    serialization:
      indent_output: true

  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true
      path: /swagger-ui.html

logging:
  level:
    root: info

