server:
  port: 8080

springdoc:
  swagger-ui:
    config-url: /api-docs-config.json
    path: /swagger-ui.html
    url: /v3/api-docs
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

spring:
  application:
    name: gateway-service

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        scheme: http
        deregister: true

    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
