server:
  port: 8080

springdoc:
  swagger-ui:
    config-url: /api-docs-config.json
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha


spring:
  application:
    name: gateway-service

  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        scheme: http
        deregister: true

    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
